### ISSUE TITLE
Adding options to data

### ISSUE THREAD

**Issue by 4rchib4ld** [phibr0/obsidian-charts#10]
Hi !
The idea behind this plugin is really cool and I have an idea to expand it a bit.

Is there a way to do something like count the occurrences of specifics words ?
I think with this you can build a "mood" tracker with the radar view.

Let's say in your daily note you say "On monday I did this, I was #mood/happy" and "On Friday I was #mood/sad".
The plugin count the occurrence of each #mood and assign them under a category like [here ](https://twitter.com/juvoni/status/1304875118087278592): 

And generate the radar view of your weekly/monthly mood.

I have no idea how complicated that would be, but I just wanted to share the idea with you !

**Comment by phibr0** [comment]
I already got some Feature Requests like that, but for me the Plugin was never intended to display vault statistics. I could add these Features but there are already some Plugins that do exactly that, my recommendation would be the [Obsidian Tracker](https://github.com/pyrochlore/obsidian-tracker) Plugin.
