### ISSUE TITLE
Can't Access Documentation

### ISSUE THREAD

**Issue by nickian** [phibr0/obsidian-charts#104]
### Describe the bug

Your documentation website is down.

### Relevant errors (if available)

```shell
This site can’t be reachedcharts.phibr0.de’s DNS address could not be found. Diagnosing the problem. DNS_PROBE_POSSIBLE
```

Strange. The site does work when I connect to a server on my VPN. Maybe it's something with my ISP.

**Comment by nickian** [comment]
When trying to connect without VPN: I get an invalid SSL certificate.

<img width="927" alt="Screenshot 2023-11-22 at 8 22 16 PM" src="https://github.com/phibr0/obsidian-charts/assets/590678/334348bf-5a95-4da9-8424-7fa31fad8175">

Or I get this in Chrome.

<img width="1015" alt="Screenshot 2023-11-22 at 8 22 59 PM" src="https://github.com/phibr0/obsidian-charts/assets/590678/ef5a2231-c821-4f4d-8650-ea7f4ae8f7d0">

**Comment by rchaklashiya** [comment]
I get the same issue, regardless of whether I use VPN or not, this is a screenshot of what I see (using Firefox):
![image](https://github.com/phibr0/obsidian-charts/assets/18043279/d16f67a5-b1e0-4c29-b01b-a5bf73f6490e)

**Comment by rchaklashiya** [comment]
I tried to access the documentation using wayback machine and it seems like something strange happened after February 2023 to that website.
See the following wayback machine links:

Last snapshot taken where there is something "normal looking" that can be read (February 2023): https://web.archive.org/web/20230204131752/https://charts.phibr0.de/
The very next snapshot taken shows almost nothing (April 2023): https://web.archive.org/web/20230402010652/https://charts.phibr0.de/
Last snapshot taken shows almost nothing (November 2023): https://web.archive.org/web/20231112093635/charts.phibr0.de/

Fortunately, it looks like you can navigate the whole site normally from the February 2023 snapshot, though of course it could probably be outdated by now.

This is very strange.

**Comment by phibr0** [comment]
Sorry, should be fixed now. The Docs are on https://charts.phib.ro/ for now
