### ISSUE TITLE
Suggestion: Adding an absolutely crucial check box or changing the defaults

### ISSUE THREAD

**Issue by mikkovedru** [phibr0/obsidian-charts#15]
People lie with statistics (and graphs). There are many ways and a lot of [famous books](https://www.goodreads.com/book/show/51291.How_to_Lie_with_Statistics) were written about it.

One of the most commonly used ways to lie is to truncate the y-axis by not starting it at 0. Very rarely it has a proper explanation, but way more often than not this is a sure way to see that the person/organization is either lying to you or are simply incompetent to talk about numbers.

Here is a good short video showing what is the problem with y-axis not starting at 0:
https://www.youtube.com/watch?v=5Qhh0Cm_TZY

I was glad to see that your great plugin has the `beginAtZero: true` option. Unfortunately, I was sad to see it neither being the default behavior nor it even being easily available via a check box. :-(

Practically any chart is unusable to me if it doesn't start at 0. And it means that every time I want to use a chart, I need to google the correct option text to add to make it proper. This is very tedious.

Could you please be so kind to:
1. change the default
2. (optionally) to make an easily available/togglable check box for people
?

Thank you for your great plugin and consideration of my request! :-)

**Comment by phibr0** [comment]
![image](https://user-images.githubusercontent.com/59741989/126860607-fcd249f2-3adb-4ff2-8cd9-0fe6e2e4f6d9.png)

I added a checkbox for this!

**Comment by mikkovedru** [comment]
@phibr0 
I already updated the plugin and confirmed that it works as it should.

What a great job you did! Thank you! :+1: :1st_place_medal:
