### ISSUE TITLE
Graph not rendered

### ISSUE THREAD

**Issue by dxcore35** [phibr0/obsidian-charts#2]
Obsidian: 0.10
OS: Mac OS, big sur

I have tried the code snippets from your example, but no graph is rendered.

**Comment by phibr0** [comment]
That's weired, could you try it again, open the developer tools (i guess cmd shift i) and copy the error? or better the whole log that's there?

**Comment by dxcore35** [comment]
Can you paste here exact code snippet? I will test it

**Comment by phibr0** [comment]
\```chart
type: bar
labels: [Monday, Tuesday, Wednesday, Thursday, Friday]
series: [[12, 5, 8, 8 , 5], [5, 8, 7, 9, 12]]
\```

This should work!

If not, please open the Devloper Tools and Copy the Error (Red)

**Comment by dxcore35** [comment]
<img width="362" alt="Screenshot 2021-01-26 at 20 49 48" src="https://user-images.githubusercontent.com/7279156/105856898-1d2e7e80-6018-11eb-8ebf-1dd35564cb21.png">

**Comment by phibr0** [comment]
Hmm it is working fine for me. Could you show me exactly what you have pasted into Obsidian? (Screenshot)

**Comment by phibr0** [comment]
If you just paste it into obsidian there will be some backslashes inbetween the \`\`\`. You will need to press ctrl + shift + v

**Comment by dxcore35** [comment]
You are funny :D I paste the code you give me.... but I remove /`/`/`... just paste copy and paste your code and you will know what im talking about.

![Uploading Screenshot 2021-01-27 at 06.18.25.png…]()

**Comment by phibr0** [comment]
1. It seems like the Block is indented by one tab/four spaces, which makes it a unfenced codeblock (It will just render as code)
2. There are more `\` in the yaml code, look at what i sent you and then what you have, Obsidian puts backslashes in front of square brackets

**Comment by dxcore35** [comment]
So?

**Comment by phibr0** [comment]
> 1. It seems like the Block is indented by one tab/four spaces, which makes it a unfenced codeblock (It will just render as code)
> 2. There are more `\` in the yaml code, look at what i sent you and then what you have, Obsidian puts backslashes in front of square brackets

You need to fix both things and then it will work

**Comment by dxcore35** [comment]
1. I don't understand this. I copy text exactly as you have
2. You send me this:

![Uploading Screenshot 2021-01-28 at 17.33.22.png…]()

**Comment by phibr0** [comment]
Yes it is trying to convert it from html to markdown but it creates errors sometimes. If it copies something wrong you can paste the raw data by using ctrl + shift + v
