### ISSUE TITLE
Charts Not Appearing in Preview Mode M1 Mac

### ISSUE THREAD

**Issue by qiwenkevin** [phibr0/obsidian-charts#21]
Charts just disappear after a while.

They render fine initially, when I had just made them. However, by the next day, when I go back to review those charts, they disappear when switching to preview mode, not even any text. 

I am running obsidian v0.12.15, and Obsidian Charts 2.5.2, which should both be the newest versions.

<img width="754" alt="Screen Shot 2021-10-04 at 3 11 29 PM" src="https://user-images.githubusercontent.com/35557152/135932072-4d80905c-ce7e-4ef9-bc14-c9e010c8fc56.png">

<img width="277" alt="Screen Shot 2021-10-04 at 3 11 23 PM" src="https://user-images.githubusercontent.com/35557152/135932079-b2b74493-0d4d-49a9-98f8-b7812dced1e8.png">

I've found a way to temporarily make them appear again but this solution is temporary as well and disappears again after a while. 

The temporary solution has been to copy the text, delete it, switch to preview mode, switch back to editor mode, paste the text back, and then it will appear again. 

<img width="692" alt="Screen Shot 2021-10-04 at 3 19 24 PM" src="https://user-images.githubusercontent.com/35557152/135932430-cda10c42-a71a-497c-ae9d-93f774ec9223.png">

If you directly copy and paste the text without going to preview mode after the text was deleted, still no charts appear.

**Comment by fmccull** [comment]
I've run into the same problem. A quicker way to get the chart to redraw is to add a space anywhere within the code block and switch to preview mode. The chart will not draw if I delete the space before switching to preview mode. So any changes to the code block, big or small, is detected and forces a redraw

The chart will disappear after opening a new note.

**Comment by fmccull** [comment]
The notes/charts that were problems before are now working as expected after update.
