### ISSUE TITLE
window.renderChart() does not work with admonition

### ISSUE THREAD

**Issue by WychWitch** [phibr0/obsidian-charts#22]
Hello! I absolutely love this plugin and I intend to  use it a lot more. However, I've run into a strange error. Using window.renderchart within dataviewjs that is *also* wrapped in a admonition block will throw the following error:

```
Evaluation Error: SyntaxError: missing ) after argument list
    at DataviewInlineApi.eval {...}
```

Using it without the block it works fine, but I make heavy use of admonition blocks for organizational purposes.

Is there something I'm doing wrong? I can post the full script that I'm using and the full error if needed, just let me know!

**Comment by phibr0** [comment]
I cannot find any error in your code, it might actually be an issue with admonitions

**Comment by phibr0** [comment]
Does it work now?

**Comment by WychWitch** [comment]
> 
> 
> Does it work now?

Sorry today has been a lot and i only just saw this! No, it's still not working (I just made sure to update and made sure admonition works with other dataviewjs blocks, and it does)

**Comment by phibr0** [comment]
Please check with the new Update

**Comment by WychWitch** [comment]
Just checked, and no it's still causing the same error. Again the code still works outside of the admonition block just not at all inside.

If there's anything else you'd like me to test let me know!

**Comment by phibr0** [comment]
![image](https://user-images.githubusercontent.com/59741989/146379956-49019cd7-34e5-4630-8a58-a47a7b41d1eb.png)
It is now working for me. Does the error still occur on your End?

**Comment by phibr0** [comment]
Ah, no I forgot this Issue has to do with the dataview api..

**Comment by WychWitch** [comment]
> Ah, no I forgot this Issue has to do with the dataview api..

SORRY I NEVER SAW THIS REPLY My github notifs were flooded with a project I accidentally subscribed to 

YES it works!!!!!!!!!!! I have no idea what changed but its totally working!! thank you!
