### ISSUE TITLE
Radar rMax not working

### ISSUE THREAD

**Issue by Jack-Chronicle** [phibr0/obsidian-charts#25]
I'm using the radar graph as a stat display for rpg games, but I want it to show a max of a bit higher than the highest stat
When I add `rMax: 15`, the highest is currently 14, it doesn't do anything. Even when I tried changing it to `rMax: 25`

![Screenshot_20211027-031914_Obsidian](https://user-images.githubusercontent.com/18507378/139037678-7f7fffbf-f2cf-496f-8dca-f0798be1b1b9.png)

![Screenshot_20211027-031920_Obsidian](https://user-images.githubusercontent.com/18507378/139037702-732ac04f-dca4-41bb-9a3b-dcfa74f17c80.png)

**Comment by rootlessweeds** [comment]
Just found the same issue.
