### ISSUE TITLE
Support for scatter type

### ISSUE THREAD

**Issue by ramon86** [phibr0/obsidian-charts#28]
Would it be possible to support the scatter chart type? I see that's available in chart.js, so I hope it wouldn't be too much work.

**Comment by phibr0** [comment]
You can create Scatter Charts via the Dataview API or by using `advanced-chart` Codeblocks. 
The default `chart` Codeblocks are just a abstraction of the Chart.js API, do you have any ideas on how to simplify the Scatter Chart Syntax?

**Comment by ramon86** [comment]
Aaah I finally got it to work, thanks! There was some confusion on my end, but it looks like issue #30 messed things up for me. Reverting back to the previous build made the scanner chart work as expected with the hint you gave. Thanks!
