### ISSUE TITLE
Gantt/Timeline support

### ISSUE THREAD

**Issue by selfire1** [phibr0/obsidian-charts#29]
Hi @phibr0 ! Thanks for the great plugin.

I'd love to see gantt/timeline support in Obsidian charts. I'm aware it's not currently supported in `chartjs`. Any chance still?

**Comment by phibr0** [comment]
Obsidian can do gantt charts natively! 
https://mermaid-js.github.io/mermaid/#/gantt

**Comment by selfire1** [comment]
Yes! What I just miss is the dataview integration. That doesn't work with mermaid but obsidian-charts supports it! 😁

**Comment by phibr0** [comment]
This will most likely not be implemented, as only chart.js is used. I am currently working on better dataview integration (without the need of dataviewjs) though, and the workaround #31 is already added.
