### ISSUE TITLE
Include date library adapter

### ISSUE THREAD

**Issue by selfire1** [phibr0/obsidian-charts#31]
Hi! I stumbled upon this trying to find a workaround for #29.

I try to set an axis to a [Time Cartesian Axis](https://www.chartjs.org/docs/latest/axes/cartesian/time.html) like so:
```
const chartData = {
    type: 'scatter',
    data: data,
    options: {
        scales: {
            x: {
                type: 'time',
                time: {
                    unit: 'day'
                }
            }
        }
    }
};
```

However, I get this error: `Error: This method is not implemented: Check that a complete date adapter is provided.`.

I'd love for a date adapter to be included in the plugin! Here is a [list of supported adapters](https://github.com/chartjs/awesome#adapters) for reference.

I am a bit out of my depth here, so there might be something I misunderstood. Thanks for the amazing plugin!

**Comment by phibr0** [comment]
I think I can just add the moment adapter, since moment is used in Obsidian anyway. Could you please try the new Release?

**Comment by selfire1** [comment]
Hi @phibr0, thanks for adding the adapter. I upgraded to `3.1.0` but can't enable Obsidian Charts.

![image](https://user-images.githubusercontent.com/70809675/142742034-34a00f6b-5217-4aac-ae3c-c23c23ea2d52.png)

**Comment by phibr0** [comment]
Thats weird.. It works fine for me. What Obsidian Version are you using?

**Comment by selfire1** [comment]
I'm on `0.12.19`. Super weird… I restarted Obsidian, my computer and deinstalled and reinstalled Obsidian Charts but can't enable it. Same error as mentioned above.
