### ISSUE TITLE
Max modifier doesnot work

### ISSUE THREAD

**Issue by Andrii256** [phibr0/obsidian-charts#37]
![image](https://user-images.githubusercontent.com/41700032/147495239-1537fab3-91a6-4735-a7e6-c8f9b36504e9.png)
![image](https://user-images.githubusercontent.com/41700032/147495265-2b7dd853-fe56-4545-8f04-33b705f28386.png)
![image](https://user-images.githubusercontent.com/41700032/147495285-c9dd7d3d-36d7-493c-92d0-d462c8c83b9e.png)
![image](https://user-images.githubusercontent.com/41700032/147495305-fcd177e7-9636-4494-b76e-65f8a8af3297.png)

**Comment by phibr0** [comment]
It is used like so: `xMax: 5`, or `yMax: 5`
I probably should make that a bit clearer in the documentation.
