### ISSUE TITLE
Refresh chart colors app switches between light/dark mode

### ISSUE THREAD

**Issue by kepano** [phibr0/obsidian-charts#45]
This is a small QoL improvement I noticed which would be nice. 

Currently when the user switches between light/dark mode, the chart colors don't change unless you close/reopen the note.

**Comment by phibr0** [comment]
I also noticed that. Already looking into it, but I want to make sure to not mess up the life-cycle management again 😅

**Comment by kepano** [comment]
The following might be useful:

> https://github.com/kepano/obsidian-minimal-settings/blob/main/main.ts#L53

> https://github.com/kepano/obsidian-system-dark-mode/blob/master/main.ts

**Comment by phibr0** [comment]
Thanks a lot!
