### ISSUE TITLE
Create chart without replacing the table, and live update

### ISSUE THREAD

**Issue by oktayacikalin** [phibr0/obsidian-charts#46]
### Describe the feature

As of now, the "create chart from table" function replaces the existing table in the markdown file.
It would be better to somehow reference the table and just update the chart's code block if the table changes.

### Does this fix a problem? If so, specify.

I've a table with monthly data about our warm / cold water and electricity meters and all our radiators.
This table is growing each month. I want to keep it, as it's much easier to add new data to it.

**Comment by phibr0** [comment]
That's actually a really good Idea, will look into it.

**Comment by oktayacikalin** [comment]
Thank you!

**Comment by oktayacikalin** [comment]
Awesome, sir! :grin: :+1:

**Comment by oktayacikalin** [comment]
I found a little bug here. The modifier spanGaps seems to convert empty cells to the value 0.
