### ISSUE TITLE
[Bug]: Plugin ID mismatch

### ISSUE THREAD

**Issue by shiMusa** [phibr0/obsidian-charts#47]
### Describe the bug

Cannot install plugin due to "Plugin ID mismatch". Version `3.3.2`

### Relevant errors (if available)

```shell
`Plugin ID mismatch`
```

### Steps to reproduce

install plugin

### Operating system

Windows

**Comment by jernejcic** [comment]
Add Mac to the Operating System list.

**Comment by phibr0** [comment]
Thats because of this ongoing Issue on GitHub: https://www.githubstatus.com/incidents/dcnvr6zym66r, will close this for now and update the manifest, so you can download 3.3.2 which is still working fine
