### ISSUE TITLE
[Bug]: Incorrect Y value of bar chart after exporting to PDF

### ISSUE THREAD

**Issue by 1-2-3** [phibr0/obsidian-charts#54]
### Describe the bug

A simple bar chart that works fine in the preview window, but the Y value is not correct after exporting the PDF.

**Y is 7**

```chart
type: bar
labels: [TESTA]
series:
  - title: AAA
    data: [7]
tension: 0.2
width: 80%
labelColors: false
fill: false
beginAtZero: false
```
preview window:
![image](https://user-images.githubusercontent.com/235531/161234302-29b4a767-d584-42db-b39b-8b2bd96230f9.png)

PDF: **Y is 6.6**
![image](https://user-images.githubusercontent.com/235531/161234492-230d6957-3d40-4230-9788-421559f202ee.png)

### Steps to reproduce

1. Create a bar chart with a Y value of 7
2. Renders without problems in preview mode
3. Exported to PDF, the Y value became 6.6

### Expected Behavior

Also has the correct Y value when exporting to PDF

### Additional context

Obsidian：v0.14.2
Obsidian Charts: v3.5.1

### Operating system

Windows

**Comment by 1-2-3** [comment]
It seems that the error of exporting PDF for the first time is not large, and there will be obvious errors when exporting PDF again.

**Comment by ChristopherKlay** [comment]
Any update on this?

It pretty much makes the addon unusable for lots of use cases, since it not only affects PDF exports, but also the convert to image functionality itself.

**Comment by RafaelGB** [comment]
same problem here, I just discovered the plugin and is awesome

**Comment by Nedreow** [comment]
I'm having a very similar problem when exporting a pie chart. Here is the [chart from the documentation](https://charts.phibr0.de/chart%20types/doughnut/) as an example:

![incomplete pie](https://user-images.githubusercontent.com/9559930/196934265-e85701e8-8740-45f6-861e-fae06188df32.PNG)

I think it is connected to the animation that plays when the chart is first displayed. My guess is that the animation is not finished when the note is converted to a pdf, resulting in a chart that is incomplete. If an option is added to disable the animation it should solve the problem.

**Comment by Wemmy0** [comment]
Welp I spend ages on a graph for school work and it's useless because of this.

**Comment by Wemmy0** [comment]
I've fixed the issue. (kinda)
**This isn't a perfect solution but if you need a quick fix:**
1. [Download the new main.js file.](https://www.dropbox.com/s/pmsx6awmn8wwd94/main.js?dl=0)
2. Go into settings > community plugins > click on the folder icon next to "Installed Plugins"
3. Go into the `obsidian-charts` folder
4. Replace the old `main.js` file with the new downloaded one
5. Restart obsidian and it should work!

I passed duration: 0 in the animation options which are passed to chart js which disables the animation.
THIS ISN'T A PERFECT SOLUTION and the animation should be automaticaly disabled when exporting as a pdf but for now this works!
