### ISSUE TITLE
[Bug]: Unable to update via Obsidian

### ISSUE THREAD

**Issue by GinoReiji** [phibr0/obsidian-charts#69]
### Describe the bug

I tried updating the plugin to the latest version but an error message showed up almost instantly, saying "Failed to install plugin". I tried a few more times but it just wouldn't work. I had this problem before, with another plugin and at that time, I decided to uninstall the plugin, hoping I could install it back again but nope, I couldn't get that plugin to be reinstalled. Don't want the same thing to happen again so I'll just stay with the older version (3.6.3) for now

### Steps to reproduce

Click on the "Update" button to update the plugin

### Expected Behavior

The plugin gets updated to the latest version

### Operating system

Windows

**Comment by phibr0** [comment]
My bad! Should be fixed now
