### ISSUE TITLE
Numbering is cut off at the top

### ISSUE THREAD

**Issue by hzb666** [phibr0/obsidian-charts#7]
The bar charts doesn't display properly, the number '15' can't be displayed completely. However, the line chart is good.
![Snipaste_2021-04-06_08-28-51](https://user-images.githubusercontent.com/29155232/113642647-e1b4ce00-96b2-11eb-9c29-4a03ff849d4b.png)

**Comment by phibr0** [comment]
I actually had that issue with some Line Charts too i think. I will look into this

**Comment by phibr0** [comment]
I am currently working on a complete rewrite of the Plugin using Chart.js instead of Chartist. This will resolve #7 and #3. This will also make the Charts a lot more interactive.
