### ISSUE TITLE
Question about sleep chart

### ISSUE THREAD

**Issue by CapSylar** [phibr0/obsidian-charts#83]
Hello,
How is the chart present in the red rectangle created (screenshot from the docs)? I've looked in the documentation but could not find any references to it.

![Pasted image 20230224202045](https://user-images.githubusercontent.com/65084960/233586864-3f7ab39a-6f7d-4a78-afe7-71d94e40afe4.png)

**Comment by YukiGasai** [comment]
Hi, it's not exactly what the image shows and my have some bugs, but use [this](https://gist.github.com/YukiGasai/82829809daa0b488fd16bc7e9c82b6c2) as sleep tracker.

![image](https://github.com/phibr0/obsidian-charts/assets/38146192/1b19eb18-aa96-4086-a25a-290badebe4a4)

**Comment by CapSylar** [comment]
Thanks for the help, I'll try this!
